### ISSUE TITLE
usb.core.USBError: [Errno 110] Operation timed out

### ISSUE THREAD

**Issue by vcidst** [Trellis-Logic/pyusb_pcap_replay#2]
Hi, thanks for writing this! I had generated a pcap file (generated by usbpcap) from sniffing this USB development board that only supports Windows currently. I converted the PCAP to PDML using Wireshark on Windows. I'm trying to reverse engineer the protocol so it can work on Raspbian.

However I get this error while I try to replay the file on Raspberry Pi running Raspbian, 

```
pi@sdpcontrol:~/Downloads/pyusb_pcap_replay-master/scripts $ sudo python usb_replay.py sdph11.pdml 
Please power down device to start
Please power on device with USB connected
Found device with VID 1110 and PID 46635
Traceback (most recent call last):
  File "usb_replay.py", line 129, in <module>
    USBReplay(VID,PID).replay(PDMLParse(sys.argv[1]))
  File "usb_replay.py", line 116, in replay
    self.do_replay_sequence(pdml)
  File "usb_replay.py", line 97, in do_replay_sequence
    buffer=dev_dict['dev'].read(dev_dict['epin'],len_bytes,DEFAULT_TIMEOUT_MS)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 833, in bulk_read
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

After this I made a slight modification to line 97, 
```
try:
    buffer=dev_dict['dev'].read(dev_dict['epin'],len_bytes,DEFAULT_TIMEOUT_MS)
except:
    print "timeout probably with ", packet
    pass
```
and similar change in the next occurrence of `DEFAULT_TIMEOUT_MS`

Running the program now gives me a different error,
```
pi@sdpcontrol:~/Downloads/pyusb_pcap_replay-master/scripts $ sudo python usb_replay.py sdph11.pdml 
Please power down device to start
Please power on device with USB connected
Found device with VID 1110 and PID 46635
timeout probably with  {'data': '0800', 'direction': 'in', 'type': 'bulk'}
Traceback (most recent call last):
  File "usb_replay.py", line 137, in <module>
    USBReplay(VID,PID).replay(PDMLParse(sys.argv[1]))
  File "usb_replay.py", line 124, in replay
    self.do_replay_sequence(pdml)
  File "usb_replay.py", line 104, in do_replay_sequence
    raise USBReplayException("Expected data " + packet['data'].upper() + " with length " + str(len(packet['data'])/2) + " bytes but found " + asciibuffer.upper() + " at packet " + str(packet_count))
__main__.USBReplayException: Expected data 0800 with length 2 bytes but found 01500080000101000001000800F60107194B328CCE416E616C6F672044657669636573C6414437363236C0CF4556414C2D414437363236464D435AC0020030C100000000009201020DFDF30300000000000000000000000001020DFCF40400000000000000000000000001020DFBF50500000000000000000000000002020D0CE300FA0000004A0100000000A00F02020D5B94014A0129016B0100000000B80B02020DF6F902B0043804280500000000E803FA020B3FBAA21200000C010000000000FA82043C44A2120010FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 at packet 13
```
If you need the device descriptors for the device, [here they are](http://shailendra.me/USB.html).

**Comment by dwalkes** [comment]
Hi @vcidst, thanks for your interest.

The error messages could definitely be better but I think what the scripts are telling you is that there's a difference between what your pdml file indicates the device should be sending back to the host and what you are receiving.  The script is waiting for the device to send back what it expects it should send back based on pdml content.

I'd recommend capturing a pcap wireshark trace of the failing sequence from the scripts and comparing to the successful trace you are trying to replay.  It looks like the pdml file you captured and are attempting to replay is expecting the device should respond to the host with 0800 at some point in the replay sequence but instead there's no response.  This could mean it's because the device doesn't always respond in the same way and you need to make the replay script more forgiving, and not necessarily expect the same response from the device every time for every packet.  Or it could mean there's some problem with the sequence being replayed which means the device didn't receive enough data or the correct data.

The scripts in their current form are pretty simple and just expect an exact match between data sent by the host and data sent back from the device.  In my case this works but for more complicated protocols this may not.

I recommend capturing and comparing wireshark traces between multiple successful runs with working scenarios and the failing replay cases and adding some more debug prints as you've started to do already.

I've also got some changes I haven't merged in yet which are helpful for sending larger pdml files and issues with ram usage.  I don't think they'd be related to what you are seeing here, but I'll try to get these merged in this week.

**Comment by vcidst** [comment]
That's odd. There's no 2 byte packet in the sniffing log. The minimum packet size in these 100 packets I see 28 bytes (size going all the way up to 65563 bytes)

**Comment by dwalkes** [comment]
If you can share the source pdml file I'll take a look.

**Comment by vcidst** [comment]
Okay, I have sniffed the data again with usbmon with an Ubuntu Host running Windows Virtual Machine. I used wireshark to convert the pcap file to PDML, [here's the link to PDML](https://github.com/vcidst/vcidst.github.io/blob/master/sdph1init.pdml)

The error I get currently is,
```
sdpctrl@sdpctrl-H61MLV2:~/Downloads/pyusb_pcap_replay-master/scripts$ sudo python usb_replay.py '/home/sdpctrl/sdph1init.pdml' 
Please power down device to start
Please power on device with USB connected
Found device with VID 1110 and PID 46635
timeout out probably with {'direction': 'out', 'type': 'bulk'}
Traceback (most recent call last):
  File "usb_replay.py", line 137, in <module>
    USBReplay(VID,PID).replay(PDMLParse(sys.argv[1]))
  File "usb_replay.py", line 124, in replay
    self.do_replay_sequence(pdml)
  File "usb_replay.py", line 113, in do_replay_sequence
    logger.debug("Wrote packet " + str(packet_count) + " with data " + packet['data'])
KeyError: 'data'
```

**Comment by dwalkes** [comment]
It looks like this is a new issue, in this case the pdml_parse script wasn't able to find the data packet in the pdml file.

Try turning on debug logging by changing the logger to use debug logging here:
https://github.com/Trellis-Logic/pyusb_pcap_replay/blob/master/scripts/pdml_parse.py#L9

This should hopefully help find out which packet it's having trouble parsing.  If not, try to add some debug logs in the failing path that will help find it.

Also, make sure to disable all protocol dissection other than USB
in wireshark using the Analyze->Enabled Protocols window as described [in Wireshark Control Protocol dissection documentation](https://www.wireshark.org/docs/wsug_html_chunked/ChCustProtocolDissectionSection.html).  Click "Disable All", then scroll down to USB and enable only the USB capture type.  Then re-export to pdml.

This prevents wireshark from incorrectly decoding packets as "PPP Unknown" or similar protocols and not including capture data in the output - which might be what happened in this case.

**Comment by vcidst** [comment]
Thanks for your response. I have made some progress with the task but not so much with this script. I replaced logging.INFO on L9 in pdml_parse.py with logging.DEBUG but that didn't change the output. So, I added a try, except KeyError in the script.

```
sdpctrl@sdpctrl-H61MLV2:~/Downloads/pyusb_pcap_replay-master/scripts$ sudo python usb_replay.py '/home/sdpctrl/sdph1-data-reexport.pdml' 
Please power down device to start
Please power on device with USB connected
Found device with VID 1110 and PID 46635
timeout out probably with {'direction': 'out', 'type': 'bulk'}
failed at L113 logger.debug() with KeyError on {'direction': 'out', 'type': 'bulk'}  packet_count:  2
Traceback (most recent call last):
  File "usb_replay.py", line 141, in <module>
    USBReplay(VID,PID).replay(PDMLParse(sys.argv[1]))
  File "usb_replay.py", line 128, in replay
    self.do_replay_sequence(pdml)
  File "usb_replay.py", line 96, in do_replay_sequence
    len_bytes=(len(packet['data'])/2)
KeyError: 'data'
```

I made this PDML after disabling all protocol dissections except USB and the USB Bulk type. It looks like I'm making the PDML file in Wireshark incorrectly so I also tried copying the PCAP to a windows machine and make a PDML there but it results in the same error.

**edit**: this error might have been caused because the format of PCAP files generated by USBSnoop or Wireshark on Windows is different from PCAP generated by usbmon. [[source](https://blog.flameeyes.eu/2017/07/reverse-engineering-notes-usb-sniffing/)]

In case you'd like to generate the PDML, here's the [PCAP](https://github.com/vcidst/vcidst.github.io/blob/master/sdph1-data_clean.pcap) made on linux with usbmon. I used a different script to replay packets. I am able to successfully initialize the board. However, I'm still clueless about how to receive data stream from the board. Here's what I know about the trace currently,

* Replaying packets 1-108 initializes the board.
* At packet 109 (use filter frame.time_relative >= 40), In the windows
software I chose sample size 1048576 and press Continuous Capture button.
* Packets 109 to 119 look somewhat similar, they probably send capture instructions with sample size to the board.
* From packet 120, 6 packets of similar structure are sent/received again
and again.
* After that, I see 6 packets of different structure at
(frame.time_relative >= 41.059593)
* Packets after (frame.time_relative >=41.073968) are of different
structure again until the end.
* Towards the end, I stop the capture from the windows software thus the
last few packets should be stop packets.

These are all only bulk transfer requests and I am in lack of ideas how to proceed looking in these packets for more information.

**Comment by dwalkes** [comment]
> edit: this error might have been caused because the format of PCAP files generated by USBSnoop or Wireshark on Windows is different from PCAP generated by usbmon.

I suspect that's correct.

Based on comparison with [your PCAP file](https://github.com/vcidst/vcidst.github.io/blob/master/sdph1-data_clean.pcap) the [erase trace](https://github.com/Trellis-Logic/pyusb_pcap_replay/tree/master/traces) I captured with usbmon on Windows 7 there are a few differences I can see in the trace which aren't handled by the scripts today.
1) It looks like the direction field is not set consistently in your trace, for instance there are packets like 110 where the source is "2.8.6" and destination is "host" but direction is "URB_BULK out" which doesn't really make sense, since a bulk out transaction would [always be host to device](http://www.beyondlogic.org/usbnutshell/usb4.shtml#Bulk).  Either the source or direction fields must be wrong.  By default the scripts trust the direction.  If this is wrong you'd need some logic [here](https://github.com/Trellis-Logic/pyusb_pcap_replay/blob/master/scripts/pdml_parse.py#L42) to override direction based on source and destination of the packet rather than reported direction.
2) There are zero length in and out transactions in the trace with data length=0 which the scripts don't attempt to support today.  These transactions have no usb.capdata field and therefore the scripts [don't create a data key here](https://github.com/Trellis-Logic/pyusb_pcap_replay/blob/master/scripts/pdml_parse.py#L50) which results in the data key errors you are seeing. The easiest way to support would probably be to check for usb.data_len field value of 0 and add a zero length data key.  I'm not sure if this will be supported in other places throughout the scripts though, for instance when attempting the [read](https://github.com/Trellis-Logic/pyusb_pcap_replay/blob/master/scripts/usb_replay.py#L97) or [write](https://github.com/Trellis-Logic/pyusb_pcap_replay/blob/master/scripts/usb_replay.py#L104) transactions.  You might need special logic there as well to handle zero length requests.

**Comment by vcidst** [comment]
> It looks like the direction field is not set consistently in your trace, for instance there are packets like 110 where the source is "2.8.6" and destination is "host" but direction is "URB_BULK out"

I found that the direction is set reverse only in packets where frame.len == 64

> There are zero length in and out transactions in the trace with data length=0 which the scripts don't attempt to support today

I do not see any frame.len == 0 packets in the capture file. However, I think you might be referring to the 64 length packets (I see bytes 36-39 tell the data length inside each packet which is zero in all 64 len packets). That's interesting. [Microsoft Hardware Dev Center](https://webcache.googleusercontent.com/search?q=cache:ZWjtY5rzp_8J:https://msdn.microsoft.com/en-us/library/windows/hardware/ff537069(v%3Dvs.85).aspx+&cd=6&hl=en&ct=clnk&gl=in&client=firefox-b-ab) mentions use of zero-length-packets in delimiting the end of transmission, it says

> Compliant USB 2.0/1.1 drivers must transmit packets of maximum size (wMaxPacketSize) and then either end the transmission by means of a packet of less than maximum size, or delimit the end of the transmission by means of a zero-length packet. The transmission is not complete until the driver sends a packet smaller than wMaxPacketSize. If the transfer size is an exact multiple of the maximum, the driver must send a zero-length delimiting packet to explicitly terminate the transfer
> 
> Delimiting the data transmission with zero-length packets, as required by the USB specification, is the responsibility of the device driver. The system USB stack will not generate these packets automatically.

I'll try to make the changes you mention and also see if replaying the trace without frame.len == 64 packets makes any difference.
